### ISSUE TITLE
Todo & idea list

### ISSUE THREAD

**Issue by jasa** [jasa/oocd-tool#3]
- [ ] A proper rpc_client API  to support GUI interfaces etc.
- [ ] tls transport layer
- [ ] A more generic remote RPC, requires authentication??.
- [ ] Some remote use of raspberry pi's GPIO ports. (terminals , semi-hosting, etc..) [erpc](https://github.com/EmbeddedRPC/erpc)
